In [1]:
#1번
import numpy as np
a=np.array([int(float((np.loadtxt('data.txt', dtype='str',delimiter='\t')[x].split(','))[y])) for x in range(0,10) for y in range(0,5)]).reshape(10,5)
a

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [2]:
aa=np.loadtxt('data.txt', dtype='int', delimiter=', ')

ValueError: invalid literal for int() with base 10: '2.000000000000000000e+00'

In [2]:
#2번
b=a[::2,::-2]
b

array([[10,  6,  2],
       [30, 26, 22],
       [50, 46, 42],
       [70, 66, 62],
       [90, 86, 82]])

In [24]:
#3번
c=(b*2).T.astype('<U11')
c

array([['20', '60', '100', '140', '180'],
       ['12', '52', '92', '132', '172'],
       ['4', '44', '84', '124', '164']], dtype='<U11')

In [25]:
#4번
d=np.append(c, c[[2,0]],0)
d

array([['20', '60', '100', '140', '180'],
       ['12', '52', '92', '132', '172'],
       ['4', '44', '84', '124', '164'],
       ['4', '44', '84', '124', '164'],
       ['20', '60', '100', '140', '180']], dtype='<U11')

In [26]:
#5번
e=np.append(np.append(d[[0,4],2:5],d[[0,4],0:2],1)[0:1],np.append(np.append(d[1:2,0:1],d[1:2,3:5]), d[1:2,1:3]).reshape(1,5),0).astype(int)
e=np.append(np.append(e,np.append(d[2:4,3:5],d[2:4,0:3],1),0), np.append(d[[0,4],2:5],d[[0,4],0:2],1)[1:2],0).astype(int)
e

array([[100, 140, 180,  20,  60],
       [ 12, 132, 172,  52,  92],
       [124, 164,   4,  44,  84],
       [124, 164,   4,  44,  84],
       [100, 140, 180,  20,  60]])

In [27]:
#6번
import pandas as pd
f=pd.Series(e[:,4], index=e[:,0]).apply(float)
f

100    60.0
12     92.0
124    84.0
124    84.0
100    60.0
dtype: float64

In [28]:
#7번
f[1:4]=None
f

100    60.0
12      NaN
124     NaN
124     NaN
100    60.0
dtype: float64

In [29]:
#8번
g=f.fillna(100)
g

100     60.0
12     100.0
124    100.0
124    100.0
100     60.0
dtype: float64

In [30]:
#9번
h=pd.Series(g.values/(sum(g.values)), index=g.index)
h

100    0.142857
12     0.238095
124    0.238095
124    0.238095
100    0.142857
dtype: float64